# Generated by Django 6.0.2 on 2026-03-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
