# Generated by Django 6.0.2 on 2026-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('income', 'Income'), ('expense', 'Expense')], default='sales', max_length=20),
            preserve_default=False,
        ),
    ]
