# Generated by Django 6.0.2 on 2026-03-05 10:57

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_expensecategory_unique_expense_category_per_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expense_category_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='incomecategory',
            name='unique_income_category_per_user',
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_expense_category_per_user_ci'),
        ),
        migrations.AddConstraint(
            model_name='incomecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_income_category_per_user_ci'),
        ),
    ]
