# Generated by Django 6.0.2 on 2026-03-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
